name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    # now only run on macos X.
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Upgrade cmake
        run: brew upgrade cmake

      - name: Install wget manually
        run: brew install wget

      - name: Install googletest manually
        run: brew install googletest

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_MINISTL_TEST=ON -DCMAKE_CXX_FLAGS="-Werror"

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build/Test
        run: ./Test